# Gemfile

source "https://rubygems.org"
gem "sinatra"
gem "activerecord", "6.1.4"
gem "activesupport", "6.1.4"
gem "line-bot-api"
gem "webrick"
gem "rack"
gem 'rdkafka'
gem 'json'
gem 'puma'
gem 'rackup'
gem 'eventmachine'