# require_relative 'apps/gxt-food-order/app'
# require_relative 'apps/gxt-food-extended/app'
# require_relative 'apps/gxt-cash-deposit/app'
# require_relative 'apps/gxt-gold-saving/app'
# require_relative 'apps/esm-monitor/app'
# require_relative 'apps/gxt-ptz/app'

require_relative '../apps/esm-media-stream/app'
require_relative '../apps/esm-miot-monitor/app'
require_relative '../apps/gxt-console/app'
